Cst core
CST-Group/cst pull request #42
Opened 2021-11-26 19:22 UTC by wandemberg-eldorado

### Why was it necessary?

Explain here the main objective of this PR.

### How was it done?

Summarize what was your strategy to reach the objective

### Implementation details

Go into further details about the implementation.

### How to test?

Give a concrete example on how to test what you have implemented.

### Future works

Tell us more about the next steps in this direction ;)

2021-12-06 21:48 UTC, andre-paraense approved these changes

2021-12-06 21:51 UTC, andre-paraense requested changes
Can you please bump the version from `0.7.0` to `0.8.0` both in the `build.gradle` and `README`, please, so we can release a new version after merging our PRs? Thanks! :)

2021-12-07 16:50 UTC, wandemberg-eldorado reviewed
done

2021-12-07 17:16 UTC, andre-paraense approved these changes

2021-12-07 17:17 UTC, merged