Rest
CST-Group/cst pull request #51
Opened 2023-04-14 14:06 UTC by wandemberg-eldorado

This PR contains the RESTMemory and HTTPCodelet classes, adding REST capabilities to CST

2023-04-25 20:03 UTC, rgudwin requested changes
Please check why the TestCodeletJson test is empty.

2023-04-25 20:03 UTC, rgudwin commented on src/test/java/br/unicamp/cst/io/rest/TestCodeletJson.java
Whis is this test empty ?

2023-06-19 15:04 UTC, wandemberg-eldorado commented on src/test/java/br/unicamp/cst/io/rest/TestCodeletJson.java
solved

2023-06-23 21:31 UTC, rgudwin approved these changes

2023-06-23 21:32 UTC, merged